import {AppRegistry} from 'react-native'
// import App from './src/components/App'
// import App from './src/components/HelloWorldApp'
// import App from './src/components/Bananas'
// import App from './src/components/Greeting'
// import App from './src/components/Blink'
// import App from './src/components/LotsOfStyles'
// import App from './src/components/layout/FixedDimensionsBasics'
// import App from './src/components/layout/FlexDimensionsBasics'
// import App from './src/components/layout/FlexDimensionsHorizontally'
// import App from './src/components/layout/FlexDimensionsJustify'
// import App from './src/components/layout/FlexDimensionsAlignCenter'
// import App from './src/components/inputs/PizzaTranslator'
// import App from './src/components/buttons/ButtonBasics'
// import App from './src/components/buttons/Touchables'
import App from './src/components/IScrolledDown'

AppRegistry.registerComponent('reactNativeApp', () => App)
