import {AppRegistry} from 'react-native'
// import App from './src/App'
// import App from './src/HelloWorldApp'
// import App from './src/Bananas'
// import App from './src/Greeting'
// import App from './src/Blink'
// import App from './src/LotsOfStyles'
// import App from './src/layout/FixedDimensionsBasics'
// import App from './src/layout/FlexDimensionsBasics'
// import App from './src/layout/FlexDimensionsHorizontally'
// import App from './src/layout/FlexDimensionsJustify'
// import App from './src/layout/FlexDimensionsAlignCenter'
// import App from './src/inputs/PizzaTranslator'
// import App from './src/buttons/ButtonBasics'
import App from './src/buttons/Touchables'

AppRegistry.registerComponent('reactNativeApp', () => App)
